export const actionTypes = {
  USER_INPUT_START: 'USER_INPUT_START',
  USER_INPUT_END: 'USER_INPUT_END',
  START_GAME: 'START_GAME',
  PAUSE_GAME: 'PAUSE_GAME',
  RESUME_GAME: 'RESUME_GAME',
  GAME_OVER: 'GAME_OVER',
  GAME_LOOP_TICK: 'GAME_LOOP_TICK',
  RESET_GAME_STATE: 'RESET_GAME_STATE',
  SET_PLAYER_POSITION: 'SET_PLAYER_POSITION',
  CHOP_START: 'CHOP_START',
  CHOP_END: 'CHOP_END'
}

export const userInputTypes = {
  LEFT: -1,
  RIGHT: 1,
  SELECT: 'SELECT',
  BACK: 'BACK'
}

export const gameStatuses = {
  TITLE_SCREEN: 'TITLE_SCREEN',
  PLAYING: 'PLAYING',
  GAME_OVER: 'GAME_OVER',
  PAUSED: 'PAUSED'
}

export const COUNTDOWN_RATE_MS = 50
